DROP DATABASE IF EXISTS ecommerce;
CREATE DATABASE ecommerce;
USE ecommerce;
CREATE TABLE teddyproducts (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(200) NOT NULL,
    CATEGORY VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID)
);

select * from teddyproducts;

SELECT DISTINCT CATEGORY FROM teddyproducts;
SELECT CATEGORY, COUNT(*) FROM teddyproducts GROUP BY CATEGORY;

